// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDk1JuD_1cPyD7bpO_pTCykcenWbLm9xQ',
    appId: '1:1078273485481:web:6b615b4f5d9badc19e97b8',
    messagingSenderId: '1078273485481',
    projectId: 'tkconnect-b4b64',
    authDomain: 'tkconnect-b4b64.firebaseapp.com',
    storageBucket: 'tkconnect-b4b64.appspot.com',
    measurementId: 'G-50W2F65C6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpIKX-_4TYzBvnBDvk2f0BoDKCcUaNmU',
    appId: '1:1078273485481:android:e94e850ef32a36ba9e97b8',
    messagingSenderId: '1078273485481',
    projectId: 'tkconnect-b4b64',
    storageBucket: 'tkconnect-b4b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1xDsfqoJ7l2fBkg23p8oNs1fiM8vaH4',
    appId: '1:1078273485481:ios:9c4ed6376485b4269e97b8',
    messagingSenderId: '1078273485481',
    projectId: 'tkconnect-b4b64',
    storageBucket: 'tkconnect-b4b64.appspot.com',
    iosBundleId: 'codespynner.io.tkconnect',
  );
}
